import React, { useState } from 'react';
import {
  Users,
  Eye,
  DollarSign,
  MousePointerClick,
  Clock,
  TrendingUp,
  ArrowUpRight,
  Sparkles,
  Info,
} from 'lucide-react';
import { CREATOR_OVERVIEW } from '../../data/mockDashboardData';

export const CreatorOverview: React.FC = () => {
  const [showTooltip, setShowTooltip] = useState(false);

  const cards = [
    {
      title: 'Estimated Subscribers',
      value: CREATOR_OVERVIEW.subscribers,
      change: CREATOR_OVERVIEW.subscribersChange,
      icon: Users,
      color: 'from-red-500 to-rose-600',
      isPositive: true,
      sparkline: [40, 48, 52, 60, 75, 82, 95],
    },
    {
      title: 'Predicted Views',
      value: CREATOR_OVERVIEW.totalViews,
      change: CREATOR_OVERVIEW.viewsChange,
      icon: Eye,
      color: 'from-rose-500 to-pink-600',
      isPositive: true,
      sparkline: [30, 45, 38, 70, 85, 90, 110],
    },
    {
      title: 'Predicted Revenue',
      value: CREATOR_OVERVIEW.estimatedRevenue,
      change: CREATOR_OVERVIEW.revenueChange,
      icon: DollarSign,
      color: 'from-emerald-500 to-teal-600',
      isPositive: true,
      sparkline: [200, 320, 280, 500, 720, 890, 1200],
    },
    {
      title: 'AI CTR Prediction',
      value: CREATOR_OVERVIEW.avgCtr,
      change: CREATOR_OVERVIEW.ctrChange,
      icon: MousePointerClick,
      color: 'from-amber-500 to-orange-600',
      isPositive: true,
      sparkline: [6.2, 7.1, 6.8, 8.4, 9.1, 9.4, 10.2],
    },
    {
      title: 'Estimated Watch Time',
      value: CREATOR_OVERVIEW.watchTimeHours,
      change: CREATOR_OVERVIEW.watchTimeChange,
      icon: Clock,
      color: 'from-blue-500 to-indigo-600',
      isPositive: true,
      sparkline: [100, 120, 115, 140, 160, 175, 184],
    },
    {
      title: 'Avg View Duration',
      value: CREATOR_OVERVIEW.avgViewDuration,
      change: '+42s vs target',
      icon: TrendingUp,
      color: 'from-violet-500 to-purple-600',
      isPositive: true,
      sparkline: [6, 6.5, 7, 7.8, 8.2, 8.5, 8.7],
    },
  ];

  return (
    <div className="space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <div className="flex items-center gap-2 relative">
            <h2 className="text-lg font-black text-white tracking-tight flex items-center gap-2">
              AI Creator Intelligence Dashboard
            </h2>

            {/* Information Icon & Tooltip */}
            <div className="relative group/info cursor-pointer">
              <button
                onClick={() => setShowTooltip(!showTooltip)}
                onMouseEnter={() => setShowTooltip(true)}
                onMouseLeave={() => setShowTooltip(false)}
                className="text-zinc-400 hover:text-red-400 transition p-1 rounded-full bg-white/5 border border-white/10 hover:border-red-500/40"
                aria-label="Simulation Notice"
              >
                <Info className="w-4 h-4 text-red-400" />
              </button>

              {/* Tooltip Overlay */}
              {showTooltip && (
                <div className="absolute left-0 top-7 z-50 w-72 p-3 bg-[#181818] border border-red-500/40 rounded-xl shadow-2xl text-xs text-zinc-200 animate-in fade-in zoom-in-95 backdrop-blur-2xl">
                  <div className="flex items-start gap-2">
                    <Info className="w-4 h-4 text-red-500 shrink-0 mt-0.5" />
                    <p className="leading-snug">
                      This dashboard demonstrates simulated analytics generated by AI and is not connected to a live YouTube account.
                    </p>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Small required note below title */}
          <p className="text-xs text-zinc-400 mt-1 font-medium">
            All analytics shown below are AI-generated demo predictions for prototype purposes.
          </p>
        </div>

        <div className="flex items-center gap-2 text-xs">
          <span className="px-3 py-1 rounded-full bg-red-500/10 border border-red-500/30 text-red-400 font-bold flex items-center gap-1.5 shadow-sm">
            <Sparkles className="w-3.5 h-3.5" /> AI Target: +25% RPM Peak
          </span>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4">
        {cards.map((card, idx) => {
          const Icon = card.icon;

          return (
            <div
              key={idx}
              className="glass-card glass-card-hover rounded-2xl p-4 border border-white/10 relative overflow-hidden flex flex-col justify-between group"
            >
              {/* Subtle top border color line */}
              <div
                className={`absolute top-0 left-0 right-0 h-1 bg-gradient-to-r ${card.color}`}
              ></div>

              <div>
                <div className="flex items-center justify-between text-zinc-400 mb-2">
                  <span className="text-xs font-semibold text-zinc-400 truncate">
                    {card.title}
                  </span>
                  <div
                    className={`w-7 h-7 rounded-lg bg-gradient-to-br ${card.color} flex items-center justify-center text-white shadow-md`}
                  >
                    <Icon className="w-4 h-4" />
                  </div>
                </div>

                <div className="mt-1">
                  <span className="text-xl font-extrabold text-white tracking-tight font-sans">
                    {card.value}
                  </span>
                </div>
              </div>

              <div className="mt-3 pt-2 border-t border-white/5 flex items-center justify-between text-[11px]">
                <span className="text-emerald-400 font-bold flex items-center gap-0.5">
                  <ArrowUpRight className="w-3 h-3" />
                  {card.change}
                </span>

                {/* Mini SVG Sparkline */}
                <div className="w-12 h-4 opacity-60 group-hover:opacity-100 transition">
                  <svg className="w-full h-full" viewBox="0 0 50 20">
                    <path
                      d={`M 0 ${20 - card.sparkline[0] / 10} L 8 ${
                        20 - card.sparkline[1] / 10
                      } L 16 ${20 - card.sparkline[2] / 10} L 24 ${
                        20 - card.sparkline[3] / 10
                      } L 32 ${20 - card.sparkline[4] / 10} L 40 ${
                        20 - card.sparkline[5] / 10
                      } L 50 ${20 - card.sparkline[6] / 10}`}
                      fill="none"
                      stroke="#FF0000"
                      strokeWidth="2"
                    />
                  </svg>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
